name: CI - Cypress API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: cypress-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci

      - name: Run Cypress (API only)
        run: |
          npx cypress run --headless --spec "cypress/e2e/api.*.cy.js"

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-api
          path: cypress/videos

      - name: Upload screenshots (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-api
          path: cypress/screenshots
